### ISSUE TITLE
Cannot find name '__TEST__'

### ISSUE THREAD

**Issue by Frankaus** [iendeavor/vue-use-popperjs#1]
node_modules/vue-use-popperjs/src/Popper.vue:143:14 - error TS2304: Cannot find name '__TEST__' when running build test on our app.

`declare const __TEST__: boolean;` is declared in within the `global.d.ts` file. Though the computed value `role` requires the the const __TEST__ to run its
`const role = computed(() =>
      typeof __TEST__ === "undefined" && visible.value
        ? "vue-use-popperjs-" + popperUid++
        : undefined
    );`

**Comment by soc221b** [comment]
@Frankaus Thanks you for your feedback :bow:, fixed in v2.2.6.

**Comment by Frankaus** [comment]
Thank you so much! Really appreciate:)
