### ISSUE TITLE
Rest parameter 'args' implicitly has an 'any[]' type in `MaybeTransition`

### ISSUE THREAD

**Issue by tomhooijenga** [iendeavor/vue-use-popperjs#2]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1853235/156583832-78833033-369b-41c5-8bce-a2b69599b4a1.png)

`MaybeTransition` uses implicit any to type the event args. This causes errors in strict typescript configurations. Additionally, there is no `.d.ts` file, causing typescript to use the source to do type checking instead of the provided types.

**To Reproduce** 

Check types with vue-tsc: `npx vue-tsc --noEmit`

**Expected behavior**

It should produce no error.

**Additional context** 
node 16.13.1
vue-tsc 0.32.0

**Comment by soc221b** [comment]
Thank you for your feedback 😄 , fixed and released in `v2.3.1`.
